services:

  # https://github.com/uptrace/uptrace/blob/master/example/docker/docker-compose.yml
  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    restart: on-failure
    environment:
      CLICKHOUSE_DB: uptrace
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ports:
      - '8123:8123'
      - '9000:9000'

  mysql:
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
#      - MYSQL_USER=petclinic
#      - MYSQL_PASSWORD=petclinic
#      - MYSQL_DATABASE=petclinic
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d:ro
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
#    profiles:
#      - mysql

  postgres:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_PASSWORD=petclinic
#      - POSTGRES_USER=petclinic
#      - POSTGRES_DB=petclinic
#    profiles:
#      - postgres
    volumes:
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data

  otelcol:
    image: otel/opentelemetry-collector:0.109.0
    volumes:
      - ./docker/otelcol/config.yaml:/etc/otelcol/config.yaml
      - ./local/logs/:/logs/ # At least on Linux, you may need: chmod a+wx ./local/logs/
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver

  # TODO mailpit for testing email alerts

  # https://github.com/uptrace/uptrace/blob/master/example/docker/docker-compose.yml
  uptrace:
    image: 'uptrace/uptrace:1.7.7'
    #image: 'uptrace/uptrace-dev:latest'
    #restart: on-failure
    volumes:
      - ./docker/uptrace/uptrace.yml:/etc/uptrace/uptrace.yml
    #environment:
    #  - DEBUG=2
    ports:
      - '14317:14317'
      - '14318:14318'
    depends_on:
      - clickhouse
      - postgres

  openobserve:
    #image: openobserve/openobserve:v0.12.1-simd
    image: openobserve/openobserve:v0.12.1
    #restart: unless-stopped
    environment:
      ZO_TELEMETRY: "false"
      ZO_META_STORE: "postgres"
      ZO_META_POSTGRES_DSN: "postgres://openobserve:openobserve@postgres:5432/openobserve"
      #ZO_META_STORE: "mysql"
      #ZO_META_MYSQL_DSN: "mysql://openobserve:openobserve@mysql:3306/openobserve"
      ZO_ROOT_USER_EMAIL: "root@example.com"
      ZO_ROOT_USER_PASSWORD: "Complexpass#123"
    ports:
      - "5080:5080"
    volumes:
      - openobserve-data:/data

volumes:
  clickhouse-data:
  mysql-data:
  postgres-data:
  openobserve-data:
