services:

  mysql:
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
#      - MYSQL_USER=petclinic
#      - MYSQL_PASSWORD=petclinic
#      - MYSQL_DATABASE=petclinic
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d:ro
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    profiles:
      - mysql

  postgres:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_PASSWORD=petclinic
#      - POSTGRES_USER=petclinic
#      - POSTGRES_DB=petclinic
    profiles:
      - postgres
    volumes:
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data

  otelcol:
    image: otel/opentelemetry-collector:0.109.0
    volumes:
      - ./docker/otelcol/config.yaml:/etc/otelcol/config.yaml
      - ./local/logs/:/logs/ # At least on Linux, you may need: chmod a+wx ./local/logs/
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver

volumes:
  mysql-data:
  postgres-data:
