receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  otlp/2:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55690

exporters:
  debug:
    verbosity: detailed
  #  file:
  #    path: /logs/logs.json
  file/traces:
    path: /logs/traces.json
  file/logs:
    path: /logs/logs.json
  file/metrics:
    path: /logs/metrics.json
  otlp/openobserve:
    #endpoint: http://openobserve:5080/api/default # http
    endpoint: openobserve:5081 # grpc
    tls: { insecure: true }
    headers:
      organization: default
      stream-name: default
      #Authorization: Basic%20cm9vdEBleGFtcGxlLmNvbTpDb21wbGV4cGFzcyMxMjM=
      Authorization: Basic cm9vdEBleGFtcGxlLmNvbTp1RWJyaXQ1eThhOXpKVkNn
  otlp/uptrace:
    endpoint: http://uptrace:14317
    tls: { insecure: true }
    headers:
      uptrace-dsn: 'http://project2_secret_token@localhost:14318?grpc=14317'

processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions:
    - health_check
    - pprof
    - zpages
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters:
        - debug
        - file/traces
        - otlp/openobserve
        - otlp/uptrace
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters:
        - debug
        - file/metrics
        - otlp/openobserve
        - otlp/uptrace
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters:
        - debug
        - file/logs
        - otlp/openobserve
        - otlp/uptrace
