receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  otlp/2:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55690

exporters:
  debug:
    verbosity: detailed
  #  file:
  #    path: /logs/logs.json
  file/traces:
    path: /logs/traces.json
  file/logs:
    path: /logs/logs.json
  file/metrics:
    path: /logs/metrics.json
  otlp/uptrace:
    endpoint: http://uptrace:14317
    tls: { insecure: true }
    headers:
      uptrace-dsn: 'http://project2_secret_token@localhost:14318?grpc=14317'

processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions:
    - health_check
    - pprof
    - zpages
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters:
        - debug
        - file/traces
        - otlp/uptrace
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters:
        - debug
        - file/metrics
        - otlp/uptrace
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters:
        - debug
        - file/logs
        - otlp/uptrace
